### PR TITLE
Fix test failures

### PR DESCRIPTION
**Pull request by flyerhzm**

### CODE REVIEW

**Comment by flyerhzm** [comment]
please merge it, redeploy and remove all current hourly_stat and daily_stat

**Comment by 0x1b2c** [comment]
Yes, I've migrated data from old system and need your pull request to finally finish the migration.

**Comment by flyerhzm** [comment]
if you create a panel on echidna.transi.st, you will see current segment didn't work. It's fixed in better-segment-algorithm branch, which is why you need to delete all HourlyStat and DailyStat after next deployment

**Comment by 0x1b2c** [comment]
Yes, I already noticed about the segmentation issue, also need to load
dictionary in Sidekiq worker. And I already have the code to erase
data carefully before migration, in the migration rake file.

**Comment by flyerhzm** [comment]
nice

**Pull request merged**
