### PR TITLE
New users sampling

### PR DESCRIPTION
**Pull request by 0x1b2c**
Logic for the new users sampling:
1. Sample famous users as initial seeds, their `seed_level` is 0.
2. Sample followings of all know people, and increase `seed_level` by 1.
3. Repeat step 2 till seed_level increased to 3.

Users tracking also improved:
- Tencent agent create all (20) lists right after created.
- Tencent agent able to sync lists status to database.
- Tencent agent able to destroy and recreate all lists.
- People know which list tracking them so they can be untracked if necessary.

Other improvements and fix:
- Store full profile to Person#profile as Hashie::Mash.
- Expire Tencent API cache every day.

I also found the reason for duplicated tweets is, unique index on Tweet model haven't created since when we run the create_indexes task, the tweets collection already have duplicated documents. This can be fixed after we deploy this pr and reset spider progress.

### CODE REVIEW

**Comment by 0x1b2c** [comment]
We have another issue the new users sampling: In the 16009 users sampled so far on my computer, 88% of them didn't set their birth year.

**Comment by simsicon** [comment]
Thanks for those commits!

For duplicated indexes, We can also ensure index by this from further problems

``` javascript
db.accounts.ensureIndex( { username: 1 }, { unique: true, dropDups: true } )
```

according to mongo doc, http://docs.mongodb.org/manual/core/indexes/#index-creation-duplicate-dropping

**Comment by ballantyne** [comment]
seems like the site is broken again.  how does this keep happening??

**Comment by 0x1b2c** [comment]
It isn't broken. Although this pull request still awaiting for @flyerhzm 's review, we decide to run it on server since weekend coming. So we can gather enough data for next week's demo.

**Comment by flyerhzm** [comment]
/dev/mapper/echidna1-home is full again, I removed sidekiq log, it should
work soon when spider catches up again.

We have an issue to rotate logs
https://github.com/transist/echidna-rails/issues/70, but not done yet.

On Fri, Jun 14, 2013 at 11:06 PM, Scott Ballantyne <notifications@github.com

> wrote:
> 
> seems like the site is broken again. how does this keep happening??
> 
> On Fri, Jun 14, 2013 at 3:48 AM, Rainux Luo <notifications@github.com
> 
> > wrote:
> > 
> > Logic for the new users sampling:
> > 1. Sample famous users as initial seeds, their seed_level is 0.
> > 2. Sample followings of all know people, and increase seed_level by 1.
> > 3. Repeat step 2 till seed_level increased to 3.
> > 
> > Users tracking also improved:
> > - Tencent agent create all (20) lists right after created.
> > - Tencent agent able to sync lists status to database.
> > - Tencent agent able to destroy and recreate all lists.
> > - People know which list tracking them so they can be untracked if
> > 
> > necessary.
> > 
> > Other improvements and fix:
> > - Store full profile to Person#profile as Hashie::Mash.
> > - Expire Tencent API cache every day.
> > 
> > I also found the reason for duplicated tweets is, unique index on Tweet
> > model haven't created since when we run the create_indexes task, the
> > tweets
> > collection already have duplicated documents. This can be fixed after we
> > 
> > ## deploy this pr and reset spider progress.
> > 
> > You can merge this Pull Request by running
> > 
> > git pull https://github.com/transist/echidna-rails new_users_sampling
> > 
> > Or view, comment on, or merge it at:
> > 
> > https://github.com/transist/echidna-rails/pull/96
> > Commit Summary
> > - Now we have advanced account of Tencent Weibo
> > - Store full profile of tencent users in Person#profile
> > - Update bundles
> > - Skip invalid Tencent user with blank name
> > - Sample Tencent Weibo users from followings of famous
> > - Sample famous users as seed
> > - Wait less time since we have advanced account
> > - Discard the error message of kill
> > - Refactor publish_user to be able to use more flexible options
> > - Record seed person as well
> > - Use Mash for easier access Person#profile
> > - Expire Tencent API cache every day
> > - Load TencentAgent::Error class explicitly
> > - Remove old users tracking module
> > - Sync lists from Tencent API
> > - Add logging methods to class level
> > - Users tracking with TencentList
> > - Rename TencentAgent::Error to TencentError to avoid conflict
> > - Create lists right after agent created
> > - Sync lists more carefully
> > - Delete list when destory TencentList
> > - Create lists asynchronously
> > - Build relationship between list and people after track
> > - Renew tweets gathering with new list handling
> > - Remove duplicate flag of track
> > - Update tencent agents stats
> > - Disable hot users sampling since they mostly spam
> > - Update reset_tweets_gathering_progress task
> > - Fix timing issue of spider scheduler
> > - Remove obsolete code
> > 
> > File Changes
> > - _M_ Gemfile<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-0>(1)
> > - _M_ Gemfile.lock<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-1>(69)
> > - _A_ app/assets/stylesheets/tencent_agents.css.sass<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-2>(2)
> > - _M_ app/models/person.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-3>(18)
> > - _M_ app/models/tencent_agent.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-4>(79)
> > - _M_ app/models/tencent_agent/api_calls_limiter.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-5>(4)
> > - _M_ app/models/tencent_agent/api_response_cacher.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-6>(14)
> > - _D_ app/models/tencent_agent/error.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-7>(16)
> > - _M_ app/models/tencent_agent/famous_users_sampling.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-8>(6)
> > - _M_ app/models/tencent_agent/hot_users_sampling.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-9>(4)
> > - _M_ app/models/tencent_agent/tencent_logger.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-10>(65)
> > - _M_ app/models/tencent_agent/tweets_gathering.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-11>(58)
> > - _M_ app/models/tencent_agent/users_sampling.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-12>(26)
> > - _A_
> >   app/models/tencent_agent/users_sampling_from_following_of_famous.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-13>(61)
> > - _M_ app/models/tencent_agent/users_tracking.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-14>(101)
> > - _A_ app/models/tencent_list.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-15>(98)
> > - _M_ app/views/tencent/agents/index.html.slim<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-16>(16)
> > - _A_ app/workers/create_lists_worker.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-17>(8)
> > - _M_ app/workers/person_worker.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-18>(3)
> > - _D_ app/workers/tracking_person_worker.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-19>(12)
> > - _A_ config/initializers/hashie.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-20>(17)
> > - _M_ lib/spider_scheduler.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-21>(30)
> > - _M_ lib/tasks/spider.rake<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-22>(2)
> > - _M_ lib/tasks/utility.rake<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-23>(6)
> > - _A_ lib/tencent_error.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-24>(14)
> > - _A_ spec/factories/tencent_lists.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-25>(6)
> > - _A_ spec/models/tencent_list_spec.rb<
> >   https://github.com/transist/echidna-rails/pull/96/files#diff-26>(7)
> > 
> > Patch Links:
> > - https://github.com/transist/echidna-rails/pull/96.patch
> > - https://github.com/transist/echidna-rails/pull/96.diff
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/transist/echidna-rails/pull/96#issuecomment-19462367
> .

## 

Best regards,
Richard Huang

http://huangzhimin.com
http://www.huangzhimin.comhttp://rails-bestpractices.com
https://github.com/flyerhzm http://github.com/flyerhzm
@flyerhzm

**Comment by flyerhzm** [comment]
btw, I redeployed the app

On Fri, Jun 14, 2013 at 11:19 PM, huang zhimin flyerhzm@gmail.com wrote:

> /dev/mapper/echidna1-home is full again, I removed sidekiq log, it should
> work soon when spider catches up again.
> 
> We have an issue to rotate logs
> https://github.com/transist/echidna-rails/issues/70, but not done yet.
> 
> On Fri, Jun 14, 2013 at 11:06 PM, Scott Ballantyne <
> notifications@github.com> wrote:
> 
> > seems like the site is broken again. how does this keep happening??
> > 
> > On Fri, Jun 14, 2013 at 3:48 AM, Rainux Luo <notifications@github.com
> > 
> > > wrote:
> > > 
> > > Logic for the new users sampling:
> > > 1. Sample famous users as initial seeds, their seed_level is 0.
> > > 2. Sample followings of all know people, and increase seed_level by 1.
> > > 3. Repeat step 2 till seed_level increased to 3.
> > > 
> > > Users tracking also improved:
> > > - Tencent agent create all (20) lists right after created.
> > > - Tencent agent able to sync lists status to database.
> > > - Tencent agent able to destroy and recreate all lists.
> > > - People know which list tracking them so they can be untracked if
> > > 
> > > necessary.
> > > 
> > > Other improvements and fix:
> > > - Store full profile to Person#profile as Hashie::Mash.
> > > - Expire Tencent API cache every day.
> > > 
> > > I also found the reason for duplicated tweets is, unique index on Tweet
> > > model haven't created since when we run the create_indexes task, the
> > > tweets
> > > collection already have duplicated documents. This can be fixed after we
> > > 
> > > ## deploy this pr and reset spider progress.
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/transist/echidna-rails new_users_sampling
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/transist/echidna-rails/pull/96
> > > Commit Summary
> > > - Now we have advanced account of Tencent Weibo
> > > - Store full profile of tencent users in Person#profile
> > > - Update bundles
> > > - Skip invalid Tencent user with blank name
> > > - Sample Tencent Weibo users from followings of famous
> > > - Sample famous users as seed
> > > - Wait less time since we have advanced account
> > > - Discard the error message of kill
> > > - Refactor publish_user to be able to use more flexible options
> > > - Record seed person as well
> > > - Use Mash for easier access Person#profile
> > > - Expire Tencent API cache every day
> > > - Load TencentAgent::Error class explicitly
> > > - Remove old users tracking module
> > > - Sync lists from Tencent API
> > > - Add logging methods to class level
> > > - Users tracking with TencentList
> > > - Rename TencentAgent::Error to TencentError to avoid conflict
> > > - Create lists right after agent created
> > > - Sync lists more carefully
> > > - Delete list when destory TencentList
> > > - Create lists asynchronously
> > > - Build relationship between list and people after track
> > > - Renew tweets gathering with new list handling
> > > - Remove duplicate flag of track
> > > - Update tencent agents stats
> > > - Disable hot users sampling since they mostly spam
> > > - Update reset_tweets_gathering_progress task
> > > - Fix timing issue of spider scheduler
> > > - Remove obsolete code
> > > 
> > > File Changes
> > > - _M_ Gemfile<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-0>(1)
> > > - _M_ Gemfile.lock<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-1>(69)
> > > - _A_ app/assets/stylesheets/tencent_agents.css.sass<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-2>(2)
> > > - _M_ app/models/person.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-3>(18)
> > > - _M_ app/models/tencent_agent.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-4>(79)
> > > - _M_ app/models/tencent_agent/api_calls_limiter.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-5>(4)
> > > - _M_ app/models/tencent_agent/api_response_cacher.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-6>(14)
> > > - _D_ app/models/tencent_agent/error.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-7>(16)
> > > - _M_ app/models/tencent_agent/famous_users_sampling.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-8>(6)
> > > - _M_ app/models/tencent_agent/hot_users_sampling.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-9>(4)
> > > - _M_ app/models/tencent_agent/tencent_logger.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-10>(65)
> > > - _M_ app/models/tencent_agent/tweets_gathering.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-11>(58)
> > > - _M_ app/models/tencent_agent/users_sampling.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-12>(26)
> > > - _A_
> > >   app/models/tencent_agent/users_sampling_from_following_of_famous.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-13>(61)
> > > - _M_ app/models/tencent_agent/users_tracking.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-14>(101)
> > > - _A_ app/models/tencent_list.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-15>(98)
> > > - _M_ app/views/tencent/agents/index.html.slim<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-16>(16)
> > > - _A_ app/workers/create_lists_worker.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-17>(8)
> > > - _M_ app/workers/person_worker.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-18>(3)
> > > - _D_ app/workers/tracking_person_worker.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-19>(12)
> > > - _A_ config/initializers/hashie.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-20>(17)
> > > - _M_ lib/spider_scheduler.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-21>(30)
> > > - _M_ lib/tasks/spider.rake<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-22>(2)
> > > - _M_ lib/tasks/utility.rake<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-23>(6)
> > > - _A_ lib/tencent_error.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-24>(14)
> > > - _A_ spec/factories/tencent_lists.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-25>(6)
> > > - _A_ spec/models/tencent_list_spec.rb<
> > >   https://github.com/transist/echidna-rails/pull/96/files#diff-26>(7)
> > > 
> > > Patch Links:
> > > - https://github.com/transist/echidna-rails/pull/96.patch
> > > - https://github.com/transist/echidna-rails/pull/96.diff
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/transist/echidna-rails/pull/96#issuecomment-19462367
> > .
> 
> ## 
> 
> Best regards,
> Richard Huang
> 
> http://huangzhimin.com
>  http://www.huangzhimin.comhttp://rails-bestpractices.com
> https://github.com/flyerhzm http://github.com/flyerhzm
> @flyerhzm

## 

Best regards,
Richard Huang

http://huangzhimin.com
http://www.huangzhimin.comhttp://rails-bestpractices.com
https://github.com/flyerhzm http://github.com/flyerhzm
@flyerhzm

**Comment by 0x1b2c** [comment]
Oh I forgot about rotate logs from spider/sidekiq, will do it soon.

You mean /home full? Really? It now has 692GB free space, sidekiq consumed this large space?

**Comment by 0x1b2c** [comment]
Also I noticed the users sampling is much slower than on my computer, so after several hours we only sampled 9k users. Will try to make it faster.

**Comment by ballantyne** [comment]
seems like it is still not working.  was it supposed to be fixed

**Comment by flyerhzm** [comment]
Rainux, there seems something wrong in spider, it didn't collect any tweet
from tencent weibo.

On Sat, Jun 15, 2013 at 9:19 AM, Scott Ballantyne
notifications@github.comwrote:

> seems like it is still not working. was it supposed to be fixed
> 
> On Fri, Jun 14, 2013 at 11:34 PM, Rainux Luo notifications@github.comwrote:
> 
> > Also I noticed the users sampling is much slower than on my computer, so
> > after several hours we only sampled 9k users. Will try to make it
> > faster.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/transist/echidna-rails/pull/96#issuecomment-19464261>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/transist/echidna-rails/pull/96#issuecomment-19489139
> .

## 

Best regards,
Richard Huang

http://huangzhimin.com
http://www.huangzhimin.comhttp://rails-bestpractices.com
https://github.com/flyerhzm http://github.com/flyerhzm
@flyerhzm

**Comment by 0x1b2c** [comment]
I disabled the tweets gathering since if the lists are not full filled with members, tweets gathering can't gather all tweets of all members. But now I submitted a patch to make tweets gathering only gather tweets from the lists full filled. You should see tweets soon.

**Pull request merged**
